-- Millitime Database Schema - Crypto Signals Bot

-- Create users table
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  username VARCHAR(100) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create watchlist table (coins users want to monitor)
CREATE TABLE IF NOT EXISTS watchlist (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  coin_id VARCHAR(100) NOT NULL, -- CoinGecko coin ID (e.g., 'bitcoin', 'ethereum')
  coin_symbol VARCHAR(20) NOT NULL, -- Symbol (e.g., 'BTC', 'ETH')
  coin_name VARCHAR(100) NOT NULL, -- Name (e.g., 'Bitcoin', 'Ethereum')
  is_active BOOLEAN DEFAULT true, -- Whether monitoring is active
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, coin_id)
);

-- Create price_history table (store price data for analysis)
CREATE TABLE IF NOT EXISTS price_history (
  id SERIAL PRIMARY KEY,
  coin_id VARCHAR(100) NOT NULL,
  price DECIMAL(20, 8) NOT NULL,
  market_cap DECIMAL(20, 2),
  volume_24h DECIMAL(20, 2),
  price_change_24h DECIMAL(10, 4),
  price_change_percentage_24h DECIMAL(10, 4),
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create signals table (trading signals generated by the bot)
CREATE TABLE IF NOT EXISTS signals (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  coin_id VARCHAR(100) NOT NULL,
  coin_symbol VARCHAR(20) NOT NULL,
  signal_type VARCHAR(20) NOT NULL, -- 'BUY', 'SELL', 'HOLD'
  price DECIMAL(20, 8) NOT NULL,
  strength VARCHAR(20), -- 'STRONG', 'MODERATE', 'WEAK'
  indicators JSONB, -- Store technical indicators that triggered the signal
  message TEXT,
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_watchlist_user_id ON watchlist(user_id);
CREATE INDEX IF NOT EXISTS idx_watchlist_coin_id ON watchlist(coin_id);
CREATE INDEX IF NOT EXISTS idx_price_history_coin_id ON price_history(coin_id);
CREATE INDEX IF NOT EXISTS idx_price_history_timestamp ON price_history(timestamp);
CREATE INDEX IF NOT EXISTS idx_signals_user_id ON signals(user_id);
CREATE INDEX IF NOT EXISTS idx_signals_coin_id ON signals(coin_id);
CREATE INDEX IF NOT EXISTS idx_signals_created_at ON signals(created_at);

-- Trading settings per user (algo toggle, background, WhatsApp destination/API key)
CREATE TABLE IF NOT EXISTS trading_settings (
  user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  algo_enabled BOOLEAN DEFAULT true,
  run_in_background BOOLEAN DEFAULT true,
  whatsapp_number VARCHAR(32),
  whatsapp_api_key TEXT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create updated_at trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = CURRENT_TIMESTAMP;
   RETURN NEW;
END;
$$ language 'plpgsql';

-- Create triggers for updated_at
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_watchlist_updated_at BEFORE UPDATE ON watchlist
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_trading_settings_updated_at BEFORE UPDATE ON trading_settings
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
